# Generated by Django 3.2 on 2021-04-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0003_remove_hostservice_late_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('pay_date', models.DateTimeField(blank=True)),
                ('pay_total', models.FloatField()),
                ('type_payments', models.CharField(choices=[('deposit', 'Deposit'), ('late', 'Late')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicepayments', to='service.service')),
            ],
        ),
    ]
