# Generated by Django 3.2 on 2021-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
