# Generated by Django 3.2 on 2021-04-16 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='accounts.host')),
            ],
        ),
    ]
