# Generated by Django 3.2 on 2021-04-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=6.6, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=5.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=5.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=6.6, max_digits=9),
            preserve_default=False,
        ),
    ]
