# Generated by Django 3.2 on 2021-04-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hostavailabledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_schedule',
        ),
        migrations.AlterField(
            model_name='dog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs_of_customer', to='accounts.customer'),
        ),
    ]
