# Generated by Django 3.2 on 2021-04-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210408_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='user_name',
            new_name='username',
        ),
    ]
