# Generated by Django 3.2 on 2021-04-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210414_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='host',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='host',
            name='longitude',
        ),
    ]
