# Generated by Django 3.2 on 2021-04-18 16:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210418_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, upload_to=accounts.models.Customer.path_and_rename, verbose_name="Customer's image"),
        ),
    ]
