# Generated by Django 3.2 on 2021-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210414_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=6.6, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=5.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=6.6, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=5.5, max_digits=9),
            preserve_default=False,
        ),
    ]
