# Generated by Django 3.2 on 2021-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210408_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('host', 'Host')], max_length=10),
        ),
    ]
