# Generated by Django 3.2 on 2021-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('host', 'Host')], default='idle', max_length=20),
        ),
    ]
