# Generated by Django 3.2 on 2021-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_dog_dog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('hosting', 'Hosting')], default='idle', max_length=20),
        ),
    ]
