# Generated by Django 3.2 on 2021-04-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210414_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='host',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='host',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
