# Generated by Django 3.2 on 2021-04-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210418_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostavailabledate',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='accounts.host'),
        ),
    ]
