# Generated by Django 3.2 on 2021-04-08 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210408_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accounts',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 4, 8)),
        ),
        migrations.AddField(
            model_name='accounts',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
