# Generated by Django 3.2 on 2021-04-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210411_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, upload_to='customer/', verbose_name="Customer's image"),
        ),
        migrations.AddField(
            model_name='dog',
            name='picture',
            field=models.ImageField(blank=True, upload_to='dog/', verbose_name="Dog's image"),
        ),
        migrations.AddField(
            model_name='host',
            name='picture',
            field=models.ImageField(blank=True, upload_to='host/', verbose_name="Host's image"),
        ),
    ]
