# Generated by Django 3.2 on 2021-04-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210414_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='customer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='accounts.customer'),
        ),
    ]
