# Generated by Django 3.2 on 2021-04-08 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210408_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_bio', models.TextField(max_length=100)),
                ('customer_dog_count', models.IntegerField(max_length=3)),
                ('customer_hosted_count', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='accounts',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 4, 9)),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_bio', models.TextField(max_length=100)),
                ('host_rating', models.FloatField(max_length=3)),
                ('host_hosted_count', models.IntegerField(max_length=4)),
                ('host_max', models.IntegerField(max_length=2)),
                ('host_avaliable', models.IntegerField(max_length=2)),
                ('host_area', models.FloatField(max_length=4)),
                ('host_schedule', models.TextField(blank=True, max_length=255)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('dog_bio', models.TextField(max_length=100)),
                ('dog_status', models.CharField(max_length=20)),
                ('dog_create_date', models.DateField(auto_now_add=True)),
                ('dog_dob', models.DateField(default=datetime.date(2021, 4, 9))),
                ('dog_breed', models.CharField(max_length=20)),
                ('dog_weight', models.FloatField(max_length=6)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
