# Generated by Django 3.2 on 2021-04-23 13:36

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210422_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=accounts.models.HouseImages.path_and_rename, verbose_name='House picture')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_host', to='accounts.host')),
            ],
        ),
    ]
