# Generated by Django 3.2 on 2021-04-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_houseimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_image', to='accounts.host'),
        ),
    ]
