# Generated by Django 3.2 on 2021-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_dog_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_bio',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
