# Generated by Django 3.2 on 2021-04-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_houseimages_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostavailabledate',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_available_date', to='accounts.host'),
        ),
    ]
