# Generated by Django 3.2 on 2021-04-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210412_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='accounts.customer'),
        ),
    ]
