# Generated by Django 3.2 on 2021-04-12 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20210411_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostService',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.host')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
                ('meal_price', models.FloatField(default=0.0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.host')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_status', models.CharField(max_length=10)),
                ('service_is_over_night', models.BooleanField(default=False)),
                ('service_reg_time', models.DateTimeField(default=datetime.date(2021, 4, 12))),
                ('service_end_time', models.DateTimeField(default=datetime.date(2021, 4, 12))),
                ('service_meal_per_day', models.IntegerField()),
                ('service_meal_weight', models.IntegerField(default=20)),
                ('service_is_walk', models.BooleanField(default=False)),
                ('service_is_get_dog', models.BooleanField(default=False)),
                ('service_is_deliver_dog', models.BooleanField(default=False)),
                ('service_is_dog_bath', models.BooleanField(default=False)),
                ('service_bio', models.TextField(default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.dog')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.host')),
                ('service_meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.meal')),
            ],
        ),
    ]
