# Generated by Django 3.2 on 2021-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='main_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment', 'Payment'), ('end', 'End'), ('in_progress', 'In progress')], default='pending', max_length=20),
        ),
    ]
