# Generated by Django 3.2 on 2021-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostservice',
            name='deposit_price',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='hostservice',
            name='late_price',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='service',
            name='created_deposit_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='created_late_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='days_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment', 'Payment'), ('end', 'End'), ('wait_for_progress', 'Wait for progress'), ('in_progress', 'In progress'), ('late', 'Late'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.CharField(choices=[('time_of_service', 'Time of service'), ('้host_is_waiting_to_receive_your_dog', 'Host is waiting to receive your dog'), ('caring_for_your_dog', 'Caring for your dog'), ('come_and_get_your_dog', 'Come and get your dog'), ('service_success', 'Service success'), ('you_cancel_this_service', 'You cancel this service')], max_length=40),
        ),
    ]
