# Generated by Django 3.2 on 2021-04-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.CharField(max_length=10),
        ),
    ]
