# Generated by Django 3.2 on 2021-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210426_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_start_time',
            field=models.DateTimeField(),
        ),
    ]
