# Generated by Django 3.2 on 2021-04-11 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_end_time',
            field=models.DateTimeField(default=datetime.date(2021, 4, 12)),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_reg_time',
            field=models.DateTimeField(default=datetime.date(2021, 4, 12)),
        ),
    ]
