# Generated by Django 3.2 on 2021-04-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210426_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostservice',
            name='late_price',
        ),
    ]
