# Generated by Django 3.2 on 2021-04-12 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210412_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_end_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_reg_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
