# Generated by Django 3.2 on 2021-04-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_hostservice_late_price'),
        ('service', '0004_service_is_customer_receive_dog'),
    ]

    operations = [
    ]
