# Generated by Django 3.2 on 2021-04-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('payment', '0001_initial'),
        ('accounts', '0003_accounts_account_number'),
        ('service', '0005_merge_20210428_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
