# Generated by Django 3.2 on 2021-04-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_merge_20210428_1946'),
        ('service', '0006_rename_service_services'),
    ]

    operations = [
    ]
