# Generated by Django 3.2 on 2021-04-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_merge_20210428_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_price',
            new_name='meal_price_per_gram',
        ),
    ]
