# Generated by Django 3.2 on 2021-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_meal_price_meal_meal_price_per_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
