# Generated by Django 3.2 on 2021-04-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_services_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='additional_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_service', to='service.hostservice'),
        ),
    ]
