# Generated by Django 3.2 on 2021-04-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_services_additional_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_meal_type',
            field=models.IntegerField(),
        ),
    ]
