# Generated by Django 3.2 on 2021-04-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_services_service_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_meal_per_day',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_service_meal_type', to='service.meal'),
        ),
    ]
