# Generated by Django 3.2 on 2021-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20210429_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostservice',
            name='enable_bath_dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostservice',
            name='enable_delivery_dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostservice',
            name='enable_dog_walk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostservice',
            name='enable_get_dog',
            field=models.BooleanField(default=False),
        ),
    ]
