# Generated by Django 3.2 on 2021-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_services_service_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
