# Generated by Django 3.2 on 2021-05-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_services_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_is_over_night',
        ),
    ]
