# Generated by Django 3.2 on 2021-05-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_services_service_is_over_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_bio',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
