# Generated by Django 3.2 on 2021-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_services_service_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_reply_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
